# Generated by Django 4.1.5 on 2023-02-15 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='DpReplyUsername',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='DpUsername',
        ),
        migrations.RemoveField(
            model_name='recentlyopenedspace',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='recentlyopenedspace',
            name='Name',
        ),
        migrations.AlterField(
            model_name='channelmembers',
            name='Member',
            field=models.ManyToManyField(related_name='chMembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='Message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='Reply',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
