# Generated by Django 4.1.5 on 2023-02-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0002_alter_members_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
