# Generated by Django 4.1.5 on 2023-02-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0003_alter_recentlyopenedspace_lastopened'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='PeopleAdded',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='TotalPeople',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
