# Generated by Django 4.1.5 on 2023-02-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0004_invitelink_peopleadded_invitelink_totalpeople_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='User',
            new_name='email',
        ),
        migrations.AlterUniqueTogether(
            name='members',
            unique_together={('Workspace', 'email')},
        ),
    ]
