# Generated by Django 4.1.5 on 2023-02-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0005_rename_user_members_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='email',
            new_name='User',
        ),
        migrations.AlterUniqueTogether(
            name='members',
            unique_together={('Workspace', 'User')},
        ),
    ]
