# Generated by Django 4.1.5 on 2023-02-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0006_rename_email_members_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='attachment',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='channelmembers',
            name='Channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novus.channels'),
        ),
    ]
