# Generated by Django 4.1.5 on 2023-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0007_chat_attachment_alter_channelmembers_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ReplyAttachment',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
