# Generated by Django 4.1.5 on 2023-03-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0008_chat_replyattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='isClient',
            field=models.BooleanField(default=False),
        ),
    ]
