# Generated by Django 4.1.5 on 2023-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0009_workspace_isclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='isClient',
            field=models.BooleanField(default=False),
        ),
    ]
