# Generated by Django 4.1.5 on 2023-03-13 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0010_chat_isclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(blank=True, default=None, null=True)),
                ('CreatedOnDate', models.DateField(auto_now_add=True)),
                ('ExpiryDate', models.DateField()),
                ('Channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novus.channels')),
                ('Workspace', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='novus.workspace', to_field='space_id')),
            ],
        ),
    ]
