# Generated by Django 4.1.5 on 2023-03-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0011_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='CreatedOnDate',
            field=models.DateField(),
        ),
    ]
