# Generated by Django 4.1.5 on 2023-03-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0012_alter_tasks_createdondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Status',
            field=models.CharField(choices=[('In Queue', 'In Queue'), ('In Progress', 'In Progress'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='In Queue', max_length=30),
        ),
    ]
