# Generated by Django 4.1.5 on 2023-03-14 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novus', '0013_tasks_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterUniqueTogether(
            name='tasks',
            unique_together={('Workspace', 'Channel')},
        ),
    ]
